### ISSUE TITLE
Architecture Docs: Describe storage and election

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio-website#136]
- [ ] Elections
  - Which components participate in elections?
  - When do elections occur, and how are they conducted?
  - How do Fluvio elections compare with elections in other distributed systems?
- [ ] Storage
  - What is the layout of persisted objects?
  - How are checksums used?

**Comment by tjtelan** [comment]
These details are all documented within the docs now

https://www.fluvio.io/docs/architecture/spu/
https://www.fluvio.io/docs/architecture/replica-election/
https://www.fluvio.io/docs/concepts/data-consistency/
https://www.fluvio.io/docs/concepts/delivery-semantics/
