### ISSUE TITLE
Update /docs/ page with SmartStream description

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio-website#162]
SmartStreams are now a core feature of Fluvio, but we don't mention them in the front docs page. We should add a section describing what they are.

We should also do some general upkeep such as describing new language clients that are now available rather than pending.

**Comment by ajhunyady** [comment]
The document should cover:
- Immutable Store (durability)
- Data Streaming (speed)
- Smart Streams (programmability)
- WebAssembly (custom logic)
- Client libraries (development tools)

**Comment by ajhunyady** [comment]
I separated the 2 for the following reasons:
1) SmartStreams - APIs we provide
2) WebAssembly - modules provided by the user.

**Comment by tjtelan** [comment]
The current SmartModules page fulfills the intent behind this issue, so closing.

https://www.fluvio.io/smartmodules/
