### ISSUE TITLE
Docs for Fluvio CLI channels

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio-website#241]
Need docs to describe how to use CLI channels, also updates to how the installer script changed to utilize `fluvio-channel` as a frontend and how it installs the release channel specific `fluvio` binary.

This probably will go under the Installation section of the CLI docs. Perhaps within versions?

https://nightly.fluvio.io/cli/installation/versions/

**Comment by ajhunyady** [comment]
I think `versions` is fine if this is considered an advanced feature.
If we want to emphasize on it, it should be a top level section inside `INSTALLATION`.
