### ISSUE TITLE
Connector development walkthrough

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio-website#251]
Current docs cover the high-level project setup, but we could use a more detailed walkthrough where we provide an example connector project skeleton and have some example commands and outputs to set expectations for how to use connectors in development.

**Comment by nacardin** [comment]
At least for Rust

**Comment by tjtelan** [comment]
We have a guide for [Python connectors](https://www.fluvio.io/connectors/developer-guide/python-connector/).

Just realized we have 4 other examples from C that we can probably polish up too

- https://github.com/infinyon/fluvio-website/tree/master/embeds/client-examples/rust
- https://github.com/infinyon/fluvio-website/tree/master/embeds/client-examples/python
- https://github.com/infinyon/fluvio-website/tree/master/embeds/client-examples/node
- https://github.com/infinyon/fluvio-website/tree/master/embeds/client-examples/java

**Comment by ajhunyady** [comment]
It would be great to get the Python equivalent for all other languages. As @nacardin said, at the minimum we should have Rust.
