### ISSUE TITLE
getting started tutorial for mac m1 has incorrect port mappings for kind configuration

### ISSUE THREAD

**Issue by LanceEa** [infinyon/fluvio-website#259]
In the getting started tutorial for the Mac M1 it suggest using Kind and exposes the K8's cluster through various node ports.

The kind config suggest mapping ports in the **31**xxx range but the default ports used by the helm charts are **30**xxx as you can see here:
https://www.fluvio.io/docs/get-started/mac_m1/#start-a-kubernetes-cluster

The helm chart is using different ports seen here:
https://github.com/infinyon/fluvio/blob/d71161d76c15bf8646621eab7b264d1106e6f4b2/k8-util/helm/fluvio-app/values.yaml#L27

This tripped me up and took a little bit of debugging to get the cluster up and running.

I'm guessing the docs just need to be aligned with the helm chart. I'm happy to send a PR to update the docs?

**Comment by sehz** [comment]
Sorry for the outdated docs.  Yes, PR is appreciated.

**Comment by sehz** [comment]
deployed
