### ISSUE TITLE
add fluvio channel docs

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio-website#376]
copy stuff from: https://github.com/infinyon/fluvio-website/pull/263

**Comment by tjtelan** [comment]
I don't know what the desired outcome looks like. These docs are [already located in the CLI docs, in the advanced section](https://www.fluvio.io/cli/advanced/cli_channels/), and it's my opinion that there isn't anything left to do here.

The bigger task would be improving the ergonomics around fluvio channels. This will be important if we want to eventually install Fluvio via package manager, but also have an equivilent fluvio channel workflow. But that's outside the scope of docs.

**Comment by tjtelan** [comment]
I think this is documented well enough for the existing functionality. Will update when there are revisions to this workflow
