### ISSUE TITLE
Add Fluvio upgrade guide

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio-website#47]
We need a doc page on how to upgrade a Fluvio cluster. Right now we do not have an actual "upgrade" command, so the process is simply to `fluvio cluster delete` and then `fluvio cluster start`. Once we have upgrade implemented, we can update the doc to reflect the new process.

**Comment by ajhunyady** [comment]
@nicholastmosher if you could put together a quick draft on how to upgrade your local cluster, we can publish it on nightly and share with @feamcor (for feedback on his upgrade)

**Comment by nicholastmosher** [comment]
Initial version of this has been completed. We can make a new issue to improve upgrade guide once better upgrade is implemented
