### ISSUE TITLE
Bug: Master compilation returns warnings and errors.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio-website#637]
aj (github/fluvio-website) %  cargo run -- hugo 
    Finished dev [unoptimized + debuginfo] target(s) in 0.89s
     Running `target/debug/fluvio-cms hugo`
$ hugo server --watch --verbose --buildDrafts --cleanDestinationDir --disableFastRender --buildFuture --ignoreCache --baseURL http://localhost --appendPort --navigateToChanged --renderToDisk
Start building sites … 
hugo v0.97.3+extended darwin/amd64 BuildDate=unknown
INFO 2023/07/11 07:31:40 removing all files from destination that don't exist in static dirs
INFO 2023/07/11 07:31:40 syncing static files to /
WARN 2023/07/11 07:31:40 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/07/11 07:31:40 "/Users/aj/local/github/fluvio-website/content/connectors/outbound/http.md:1:1": duplicate menu entry with identifier "" in menu "HTTP"
WARN 2023/07/11 07:31:40 "/Users/aj/local/github/fluvio-website/content/connectors/outbound/kafka.md:1:1": duplicate menu entry with identifier "" in menu "Kafka"
WARN 2023/07/11 07:31:40 "/Users/aj/local/github/fluvio-website/content/connectors/_index.md:1:1": duplicate menu entry with identifier "Smart Connectors" in menu "Overview"
ERROR 2023/07/11 07:31:40 [en] REF_NOT_FOUND: Ref "/cli/local/connector": "/Users/aj/local/github/fluvio-website/content/cli/local/overview.md:18:24": page not found
Error: Error building site: logged 1 error(s)
Built in 699 ms
Error: command exited with non-zero code `hugo server --watch --verbose --buildDrafts --cleanDestinationDir --disableFastRender --buildFuture --ignoreCache --baseURL http://localhost --appendPort --navigateToChanged --renderToDisk`: 255

**Comment by tjtelan** [comment]
The problem here is the version of Hugo doesn't match what is being used on Cloudflare. I had to upgrade the version for similar build-related reasons: https://github.com/infinyon/fluvio-website/issues/589

```
HUGO_VERSION | 0.111.3
```

**Comment by ajhunyady** [comment]
Can we document this required version somewhere? 
We should also remove `netlify.toml` from the root directory as that has the old hugo version.
